# Generated by Django 5.0.4 on 2024-04-28 12:34

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Заказчик',
                'verbose_name_plural': 'Заказчики',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Dogovor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30, verbose_name='Номер договора')),
                ('date_oformlenie', models.DateField(verbose_name='Дата оформления договора')),
                ('date_ispolnenie', models.DateField(blank=True, null=True, verbose_name='Дата расторжения')),
                ('summa', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма договора')),
            ],
            options={
                'verbose_name': 'Договор',
                'verbose_name_plural': 'Договоры',
            },
        ),
        migrations.CreateModel(
            name='DogovorState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Статус договора')),
            ],
            options={
                'verbose_name': 'Статус договора',
                'verbose_name_plural': 'Статусы договора',
            },
        ),
        migrations.CreateModel(
            name='EmployerPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='Номер прайс-листа')),
                ('data', models.DateField(auto_now_add=True, verbose_name='Дата утверждения прайс-листа')),
            ],
            options={
                'verbose_name': ('Прайс-лист',),
                'verbose_name_plural': 'Прайс-листы',
            },
        ),
        migrations.CreateModel(
            name='Usluga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Наименование услуги')),
                ('description', models.TextField(verbose_name='Описание услуги')),
                ('image', models.ImageField(blank=True, upload_to='images/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='UslugaCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Категория услуги')),
                ('image', models.ImageField(blank=True, upload_to='images/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Категория услуги',
                'verbose_name_plural': 'Категории услуги',
            },
        ),
        migrations.CreateModel(
            name='ZayavkaState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Статус заявки')),
            ],
            options={
                'verbose_name': 'Статус заявки',
                'verbose_name_plural': 'Статусы заявки',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=200, null=True, verbose_name='Сообщение')),
                ('username', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор сообщения')),
            ],
            options={
                'verbose_name': ('Сообщение',),
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='Фотография сотрудника')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('date_of_employment', models.DateField(verbose_name='Дата приема на работу')),
                ('date_of_dismissal', models.DateField(blank=True, null=True, verbose_name='Дата увольнения')),
                ('employer_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.employerposition', verbose_name='Должность')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.uslugacategory', verbose_name='Категория услуги')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='StateofDogovor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата статуса')),
                ('dogovor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.dogovor', verbose_name='Договор')),
                ('employer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.employer', verbose_name='Сотрудник')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.dogovorstate', verbose_name='Статус договора')),
            ],
            options={
                'verbose_name': 'Статус в договоре',
                'verbose_name_plural': 'Статусы в договоре',
            },
        ),
        migrations.CreateModel(
            name='Position_Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_product', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость услуги')),
                ('price_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.price', verbose_name='Прайс-лист')),
                ('usluga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.usluga', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': ('Позиция прайс-листа',),
                'verbose_name_plural': 'Позиции прайс-листа',
            },
        ),
        migrations.AddField(
            model_name='usluga',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.uslugacategory', verbose_name='Категория услуги'),
        ),
        migrations.CreateModel(
            name='Zayavka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, verbose_name='Номер заявки')),
                ('date_document', models.DateField(verbose_name='Дата документа')),
                ('address', models.CharField(max_length=1000, verbose_name='Адрес исполнения')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Комментарий к заявке')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.customer', verbose_name='Заказчик')),
                ('employer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.employer', verbose_name='Сотрудник')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.position_price', verbose_name='Позиция прайс-листа')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.CreateModel(
            name='Otziv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=200, null=True, verbose_name='Отзыв')),
                ('number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.zayavka', verbose_name='Номер заявки')),
            ],
            options={
                'verbose_name': ('Отзыв',),
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='Act',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30, verbose_name='Номер акта')),
                ('date_document', models.DateField(verbose_name='Дата документа')),
                ('kolichestvo', models.CharField(max_length=30, verbose_name='Количество услуг')),
                ('summa', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Итого по позиции')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.position_price', verbose_name='Позиция прайс-листа')),
                ('zayavka', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.zayavka', verbose_name='Номер заявки')),
            ],
            options={
                'verbose_name': ('Акт выполненных работ',),
                'verbose_name_plural': 'Акты выполненных работ',
            },
        ),
        migrations.CreateModel(
            name='StateofZayavka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата статуса')),
                ('employer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.employer', verbose_name='Сотрудник')),
                ('zayavka', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.zayavka', verbose_name='Заявка')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.zayavkastate', verbose_name='Статус заявки')),
            ],
            options={
                'verbose_name': 'Статус в заявке',
                'verbose_name_plural': 'Статусы в заявке',
            },
        ),
    ]
