# Generated by Django 5.0.4 on 2024-05-08 18:31

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Act',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30, verbose_name='Номер акта')),
                ('date_document', models.DateField(verbose_name='Дата документа')),
                ('summa', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Итого')),
            ],
            options={
                'verbose_name': ('Акт выполненных работ',),
                'verbose_name_plural': 'Акты выполненных работ',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('message', models.TextField(max_length=200, null=True, verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': ('Сообщение',),
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.CreateModel(
            name='DogovorState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Статус договора')),
            ],
            options={
                'verbose_name': 'Статус договора',
                'verbose_name_plural': 'Статусы договора',
            },
        ),
        migrations.CreateModel(
            name='EmployerPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
            },
        ),
        migrations.CreateModel(
            name='Position_Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_product', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость услуги')),
            ],
            options={
                'verbose_name': ('Позиция прайс-листа',),
                'verbose_name_plural': 'Позиции прайс-листа',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='Номер прайс-листа')),
                ('data', models.DateField(auto_now_add=True, verbose_name='Дата утверждения прайс-листа')),
            ],
            options={
                'verbose_name': ('Прайс-лист',),
                'verbose_name_plural': 'Прайс-листы',
            },
        ),
        migrations.CreateModel(
            name='Usluga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('title', models.CharField(max_length=60, verbose_name='Наименование услуги')),
                ('description', models.TextField(verbose_name='Описание услуги')),
                ('image', models.ImageField(blank=True, upload_to='images/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='UslugaCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('title', models.CharField(max_length=30, verbose_name='Категория услуги')),
                ('image', models.ImageField(blank=True, upload_to='images/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Категория услуги',
                'verbose_name_plural': 'Категории услуги',
            },
        ),
        migrations.CreateModel(
            name='ZayavkaState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Статус заявки')),
            ],
            options={
                'verbose_name': 'Статус заявки',
                'verbose_name_plural': 'Статусы заявки',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('patronymic', models.CharField(blank=True, max_length=30, null=True, verbose_name='Отчество')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Заказчик',
                'verbose_name_plural': 'Заказчики',
            },
            bases=('products.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('patronymic', models.CharField(blank=True, max_length=30, null=True, verbose_name='Отчество')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='Фотография сотрудника')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('date_of_employment', models.DateField(verbose_name='Дата приема на работу')),
                ('date_of_dismissal', models.DateField(blank=True, null=True, verbose_name='Дата увольнения')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.uslugacategory', verbose_name='Категория услуги')),
                ('employer_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.employerposition', verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
            bases=('products.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Position_Act',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kolichestvo', models.CharField(max_length=30, verbose_name='Количество услуг')),
                ('itogo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Итого по позиции')),
                ('act', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.act', verbose_name='Номер акта')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.position_price', verbose_name='Позиция прайс-листа')),
            ],
            options={
                'verbose_name': ('Позиция акта выполненных работ',),
                'verbose_name_plural': 'Позиции акта выполненных работ',
            },
        ),
        migrations.AddField(
            model_name='position_price',
            name='price_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.price', verbose_name='Прайс-лист'),
        ),
        migrations.AddField(
            model_name='position_price',
            name='usluga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='positions_prices', to='products.usluga', verbose_name='Услуга'),
        ),
        migrations.AddField(
            model_name='usluga',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.uslugacategory', verbose_name='Категория услуги'),
        ),
        migrations.CreateModel(
            name='Zayavka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, verbose_name='Номер заявки')),
                ('date_document', models.DateField(verbose_name='Дата документа')),
                ('address', models.CharField(max_length=1000, verbose_name='Адрес исполнения')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Комментарий к заявке')),
                ('position', models.ManyToManyField(blank=True, null=True, to='products.position_price', verbose_name='Позиция прайс-листа')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.customer', verbose_name='Заказчик')),
                ('employer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.employer', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.CreateModel(
            name='Otziv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=200, null=True, verbose_name='Отзыв')),
                ('number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.zayavka', verbose_name='Номер заявки')),
            ],
            options={
                'verbose_name': ('Отзыв',),
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='Dogovor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30, verbose_name='Номер договора')),
                ('date_oformlenie', models.DateField(verbose_name='Дата оформления договора')),
                ('date_ispolnenie', models.DateField(blank=True, null=True, verbose_name='Дата расторжения')),
                ('summa', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма договора')),
                ('zayavka', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.zayavka', verbose_name='Номер заявки')),
            ],
            options={
                'verbose_name': 'Договор',
                'verbose_name_plural': 'Договоры',
            },
        ),
        migrations.AddField(
            model_name='act',
            name='zayavka',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.zayavka', verbose_name='Номер заявки'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1000, verbose_name='Текст отзыва')),
                ('zayavka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.zayavka', verbose_name='Завка')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.customer', verbose_name='Заказчик')),
            ],
        ),
        migrations.CreateModel(
            name='StateofZayavka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата статуса')),
                ('zayavka', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.zayavka', verbose_name='Заявка')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.zayavkastate', verbose_name='Статус заявки')),
                ('employer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.employer', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Статус в заявке',
                'verbose_name_plural': 'Статусы в заявке',
            },
        ),
        migrations.CreateModel(
            name='StateofDogovor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата статуса')),
                ('dogovor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.dogovor', verbose_name='Договор')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.dogovorstate', verbose_name='Статус договора')),
                ('employer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.employer', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Статус в договоре',
                'verbose_name_plural': 'Статусы в договоре',
            },
        ),
        migrations.AddField(
            model_name='price',
            name='employer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.employer', verbose_name='Сотрудник'),
        ),
    ]
