# Generated by Django 5.0.4 on 2024-05-08 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='date_of_employment',
            field=models.DateField(null=True, verbose_name='Дата приема на работу'),
        ),
    ]
