# Generated by Django 5.0.4 on 2024-04-28 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogovor',
            name='zayavka_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.zayavka', verbose_name='Номер заявки'),
        ),
    ]
