# Generated by Django 5.0.4 on 2024-04-29 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_dogovor_zayavka_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='employer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.employer', verbose_name='Сотрудник'),
        ),
    ]
