# Generated by Django 5.0.4 on 2024-04-30 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_price_employer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dogovor',
            old_name='zayavka_id',
            new_name='zayavka',
        ),
        migrations.RemoveField(
            model_name='act',
            name='kolichestvo',
        ),
        migrations.RemoveField(
            model_name='act',
            name='position',
        ),
        migrations.AlterField(
            model_name='act',
            name='summa',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Итого'),
        ),
        migrations.AlterField(
            model_name='act',
            name='zayavka',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.zayavka', verbose_name='Номер заявки'),
        ),
        migrations.CreateModel(
            name='Position_Act',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kolichestvo', models.CharField(max_length=30, verbose_name='Количество услуг')),
                ('itogo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Итого по позиции')),
                ('act', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.act', verbose_name='Номер акта')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.position_price', verbose_name='Позиция прайс-листа')),
            ],
            options={
                'verbose_name': ('Позиция акта выполненных работ',),
                'verbose_name_plural': 'Позиции акта выполненных работ',
            },
        ),
    ]
