# Generated by Django 5.0.4 on 2024-05-08 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_stateofzayavka_zayavka'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stateofzayavka',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stateozayvkas', to='products.zayavkastate', verbose_name='Статус заявки'),
        ),
    ]
