# Generated by Django 5.0.4 on 2024-05-10 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_stateofzayavka_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='zayavka',
            name='quantity',
            field=models.SmallIntegerField(default=0),
        ),
    ]
