# Generated by Django 5.0.4 on 2024-05-05 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_zayavka_id_dogovor_zayavka_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='patronymic',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='employer',
            name='patronymic',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Отчество'),
        ),
    ]
