# Generated by Django 5.0.4 on 2024-05-10 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_zayavka_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='zayavka',
            name='total_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
