# Generated by Django 5.0.4 on 2024-05-10 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_zayavka_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zayavka',
            name='quantity',
        ),
    ]
