# Generated by Django 5.0.4 on 2024-05-10 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_zayavka_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterField(
            model_name='zayavka',
            name='total_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Итого'),
        ),
    ]
