# Generated by Django 5.0.4 on 2024-05-10 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_comment_options_alter_zayavka_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='zayavka',
            name='positions_and_prices',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.DeleteModel(
            name='Otziv',
        ),
    ]
