# Generated by Django 4.2.7 on 2024-05-12 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_zayavka_positions_and_prices_delete_otziv'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='patronymic',
            new_name='otchestvo',
        ),
        migrations.RenameField(
            model_name='employer',
            old_name='patronymic',
            new_name='otchestvo',
        ),
        migrations.AddField(
            model_name='customuser',
            name='patronymic',
            field=models.CharField(blank=True, max_length=150, verbose_name='patronymic'),
        ),
        migrations.AlterField(
            model_name='zayavka',
            name='positions_and_prices',
            field=models.TextField(default='', max_length=1000, verbose_name='Позиции и количество'),
        ),
    ]
