# Generated by Django 4.2.7 on 2024-05-12 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_rename_patronymic_customer_otchestvo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='publication',
            field=models.BooleanField(default=False, verbose_name='Опубликовать'),
        ),
    ]
