# Generated by Django 4.2.7 on 2024-05-12 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_comment_publication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uslugacategory',
            name='title',
            field=models.CharField(max_length=60, verbose_name='Категория услуги'),
        ),
    ]
