# Generated by Django 4.2.7 on 2024-05-12 15:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_uslugacategory_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='time_send',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Время отправки'),
        ),
    ]
