# Generated by Django 4.2.7 on 2024-05-12 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_contact_time_send'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zayavka',
            name='date_document',
            field=models.DateField(verbose_name='Дата исполнения'),
        ),
    ]
