# Generated by Django 4.2.7 on 2024-05-12 17:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_zayavka_date_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='time_send',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время отправки'),
        ),
    ]
