# Generated by Django 4.2.7 on 2024-05-12 17:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_contact_time_send'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='time_send',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Время отправки'),
        ),
    ]
