# Generated by Django 4.2.7 on 2024-05-12 17:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_contact_time_send'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='data',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата отправки'),
        ),
    ]
