# Generated by Django 4.2.7 on 2024-05-13 09:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_contact_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время отправления'),
        ),
    ]
