# Generated by Django 4.2.7 on 2024-05-13 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_contact_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='datetime',
        ),
    ]
