# Generated by Django 4.2.7 on 2024-05-14 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_remove_contact_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position_price',
            name='cost_product',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость услуги, руб.'),
        ),
    ]
