# Generated by Django 4.2.7 on 2024-05-14 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_alter_position_price_cost_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zayavka',
            name='total_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Итого, руб.'),
        ),
    ]
