# Generated by Django 4.2.7 on 2024-05-14 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_alter_zayavka_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act',
            name='summa',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Итого, руб.'),
        ),
        migrations.AlterField(
            model_name='dogovor',
            name='summa',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма договора, руб.'),
        ),
        migrations.AlterField(
            model_name='position_act',
            name='itogo',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Итого по позиции, руб.'),
        ),
    ]
