# Generated by Django 4.2.7 on 2024-05-21 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_alter_act_summa_alter_dogovor_summa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usluga',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='Изображение (jpeg, png)'),
        ),
    ]
