# Generated by Django 4.2.7 on 2024-05-21 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_alter_employer_image_alter_uslugacategory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='chekbox',
            field=models.BooleanField(default=False, verbose_name='Согласие на обработку персональных данных'),
        ),
    ]
