# Generated by Django 4.2.7 on 2024-05-21 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_remove_customuser_chekbox_customer_soglasie'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='soglasie',
            field=models.BooleanField(default=False, verbose_name='Согласие на обработку персональных данных'),
        ),
    ]
