# Generated by Django 4.2.7 on 2024-05-23 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_alter_employer_image_alter_usluga_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='act',
            name='image',
            field=models.ImageField(blank=True, upload_to='documents/', verbose_name='Акт выполненных работ (.jpeg, .png)'),
        ),
        migrations.AddField(
            model_name='dogovor',
            name='image',
            field=models.ImageField(blank=True, upload_to='documents/', verbose_name='Договор (.jpeg, .png)'),
        ),
    ]
