# Generated by Django 4.2.7 on 2024-05-23 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_pretensia_pretensiastate_stateofpretensia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='act',
            name='image',
        ),
    ]
